apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubetut
    spec:
      containers:
      - name: pg-database
        image: postgres:9.6
        ports:
        - name: pg-port
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-volume
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: pg-volume-claim
